btc:
  rpcurl: "url-to-btc-client:port"
  username: "btc-rpc-user"
  password: "btc-rpc-passord"
eth:
  rpcurl: "url-to-eth-client:port"
db:
  servicename: "dbservice"
official:
  btcaddress: "official-btc-address"
  ethaddress: "official-eth-address"
  ethsecret: "secret-of-eth-official-address"

# local grpc port
ip: "ipaddress"
port: ":port"

# core service name
name: "core"
servicename: "coreservice"

# etcd config
etcdhosts : ["127.0.0.1:1234"]
etcdtimeout : 2
heartbeat: 1