btc:
  rpcurl: "url-to-btc-client:port"
  username: "btc-rpc-user"
  password: "btc-rpc-passord"
db:
  grpcurl: "url-to-grpc:port"
official:
  btcaddress: "official-btc-address"
  ethaddress: "official-eth-address"