// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/api/grpc/record/record.proto

package record

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	reply "gitlab.com/packtumi9722/huanhuanhuei/src/database/api/grpc/reply"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_NOT_FOUND StatusCode = 0
	StatusCode_PENDING   StatusCode = 1
	StatusCode_CONFIRMED StatusCode = 2
	StatusCode_FINISH    StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "NOT_FOUND",
	1: "PENDING",
	2: "CONFIRMED",
	3: "FINISH",
}

var StatusCode_value = map[string]int32{
	"NOT_FOUND": 0,
	"PENDING":   1,
	"CONFIRMED": 2,
	"FINISH":    3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{0}
}

type RecordDatum struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordDatum) Reset()         { *m = RecordDatum{} }
func (m *RecordDatum) String() string { return proto.CompactTextString(m) }
func (*RecordDatum) ProtoMessage()    {}
func (*RecordDatum) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{0}
}

func (m *RecordDatum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordDatum.Unmarshal(m, b)
}
func (m *RecordDatum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordDatum.Marshal(b, m, deterministic)
}
func (m *RecordDatum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordDatum.Merge(m, src)
}
func (m *RecordDatum) XXX_Size() int {
	return xxx_messageInfo_RecordDatum.Size(m)
}
func (m *RecordDatum) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordDatum.DiscardUnknown(m)
}

var xxx_messageInfo_RecordDatum proto.InternalMessageInfo

func (m *RecordDatum) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RecordData struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordData) Reset()         { *m = RecordData{} }
func (m *RecordData) String() string { return proto.CompactTextString(m) }
func (*RecordData) ProtoMessage()    {}
func (*RecordData) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{1}
}

func (m *RecordData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordData.Unmarshal(m, b)
}
func (m *RecordData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordData.Marshal(b, m, deterministic)
}
func (m *RecordData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordData.Merge(m, src)
}
func (m *RecordData) XXX_Size() int {
	return xxx_messageInfo_RecordData.Size(m)
}
func (m *RecordData) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordData.DiscardUnknown(m)
}

var xxx_messageInfo_RecordData proto.InternalMessageInfo

func (m *RecordData) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordID) Reset()         { *m = RecordID{} }
func (m *RecordID) String() string { return proto.CompactTextString(m) }
func (*RecordID) ProtoMessage()    {}
func (*RecordID) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{2}
}

func (m *RecordID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordID.Unmarshal(m, b)
}
func (m *RecordID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordID.Marshal(b, m, deterministic)
}
func (m *RecordID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordID.Merge(m, src)
}
func (m *RecordID) XXX_Size() int {
	return xxx_messageInfo_RecordID.Size(m)
}
func (m *RecordID) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordID.DiscardUnknown(m)
}

var xxx_messageInfo_RecordID proto.InternalMessageInfo

func (m *RecordID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RecordIDs struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordIDs) Reset()         { *m = RecordIDs{} }
func (m *RecordIDs) String() string { return proto.CompactTextString(m) }
func (*RecordIDs) ProtoMessage()    {}
func (*RecordIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{3}
}

func (m *RecordIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordIDs.Unmarshal(m, b)
}
func (m *RecordIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordIDs.Marshal(b, m, deterministic)
}
func (m *RecordIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordIDs.Merge(m, src)
}
func (m *RecordIDs) XXX_Size() int {
	return xxx_messageInfo_RecordIDs.Size(m)
}
func (m *RecordIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordIDs.DiscardUnknown(m)
}

var xxx_messageInfo_RecordIDs proto.InternalMessageInfo

func (m *RecordIDs) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Record struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromToken            *TokenDetail `protobuf:"bytes,2,opt,name=fromToken,proto3" json:"fromToken,omitempty"`
	ToToken              *TokenDetail `protobuf:"bytes,3,opt,name=toToken,proto3" json:"toToken,omitempty"`
	Exrate               float64      `protobuf:"fixed64,4,opt,name=exrate,proto3" json:"exrate,omitempty"`
	StatusCode           StatusCode   `protobuf:"varint,5,opt,name=statusCode,proto3,enum=api.grpc.record.StatusCode" json:"statusCode,omitempty"`
	StatusTime           *StatusTime  `protobuf:"bytes,6,opt,name=statusTime,proto3" json:"statusTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{4}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetFromToken() *TokenDetail {
	if m != nil {
		return m.FromToken
	}
	return nil
}

func (m *Record) GetToToken() *TokenDetail {
	if m != nil {
		return m.ToToken
	}
	return nil
}

func (m *Record) GetExrate() float64 {
	if m != nil {
		return m.Exrate
	}
	return 0
}

func (m *Record) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_NOT_FOUND
}

func (m *Record) GetStatusTime() *StatusTime {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type TokenDetail struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TokenValue           string   `protobuf:"bytes,4,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	TokenDecimal         int32    `protobuf:"varint,5,opt,name=tokenDecimal,proto3" json:"tokenDecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenDetail) Reset()         { *m = TokenDetail{} }
func (m *TokenDetail) String() string { return proto.CompactTextString(m) }
func (*TokenDetail) ProtoMessage()    {}
func (*TokenDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{5}
}

func (m *TokenDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDetail.Unmarshal(m, b)
}
func (m *TokenDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDetail.Marshal(b, m, deterministic)
}
func (m *TokenDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDetail.Merge(m, src)
}
func (m *TokenDetail) XXX_Size() int {
	return xxx_messageInfo_TokenDetail.Size(m)
}
func (m *TokenDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDetail proto.InternalMessageInfo

func (m *TokenDetail) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *TokenDetail) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *TokenDetail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenDetail) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *TokenDetail) GetTokenDecimal() int32 {
	if m != nil {
		return m.TokenDecimal
	}
	return 0
}

type StatusTime struct {
	PendingTime          int64    `protobuf:"varint,1,opt,name=pendingTime,proto3" json:"pendingTime,omitempty"`
	FinishedTime         int64    `protobuf:"varint,2,opt,name=finishedTime,proto3" json:"finishedTime,omitempty"`
	ConfirmedTime        int64    `protobuf:"varint,3,opt,name=confirmedTime,proto3" json:"confirmedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusTime) Reset()         { *m = StatusTime{} }
func (m *StatusTime) String() string { return proto.CompactTextString(m) }
func (*StatusTime) ProtoMessage()    {}
func (*StatusTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee1032e7149269, []int{6}
}

func (m *StatusTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusTime.Unmarshal(m, b)
}
func (m *StatusTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusTime.Marshal(b, m, deterministic)
}
func (m *StatusTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusTime.Merge(m, src)
}
func (m *StatusTime) XXX_Size() int {
	return xxx_messageInfo_StatusTime.Size(m)
}
func (m *StatusTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusTime.DiscardUnknown(m)
}

var xxx_messageInfo_StatusTime proto.InternalMessageInfo

func (m *StatusTime) GetPendingTime() int64 {
	if m != nil {
		return m.PendingTime
	}
	return 0
}

func (m *StatusTime) GetFinishedTime() int64 {
	if m != nil {
		return m.FinishedTime
	}
	return 0
}

func (m *StatusTime) GetConfirmedTime() int64 {
	if m != nil {
		return m.ConfirmedTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.grpc.record.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*RecordDatum)(nil), "api.grpc.record.RecordDatum")
	proto.RegisterType((*RecordData)(nil), "api.grpc.record.RecordData")
	proto.RegisterType((*RecordID)(nil), "api.grpc.record.RecordID")
	proto.RegisterType((*RecordIDs)(nil), "api.grpc.record.RecordIDs")
	proto.RegisterType((*Record)(nil), "api.grpc.record.Record")
	proto.RegisterType((*TokenDetail)(nil), "api.grpc.record.TokenDetail")
	proto.RegisterType((*StatusTime)(nil), "api.grpc.record.StatusTime")
}

func init() {
	proto.RegisterFile("src/database/api/grpc/record/record.proto", fileDescriptor_c4ee1032e7149269)
}

var fileDescriptor_c4ee1032e7149269 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x6d, 0x12, 0x96, 0x2e, 0x5f, 0xb7, 0x51, 0x59, 0x02, 0x42, 0x36, 0x50, 0x65, 0x21, 0x31,
	0xb8, 0x68, 0x45, 0x91, 0xb8, 0x00, 0x09, 0x24, 0x9a, 0xb6, 0xe4, 0x82, 0x14, 0x79, 0x1d, 0x17,
	0xdc, 0x20, 0xaf, 0x71, 0x57, 0x8b, 0xb6, 0x89, 0x62, 0x57, 0xea, 0x5e, 0x06, 0x89, 0x57, 0xe3,
	0x49, 0x50, 0x6c, 0xb7, 0x4d, 0x37, 0x65, 0xe2, 0xc6, 0x89, 0xcf, 0x77, 0xce, 0xf9, 0x7e, 0x64,
	0x1b, 0x5e, 0x89, 0x7c, 0xd2, 0x49, 0xa8, 0xa4, 0x57, 0x54, 0xb0, 0x0e, 0xcd, 0x78, 0xe7, 0x3a,
	0xcf, 0x26, 0x9d, 0x9c, 0x4d, 0xd2, 0x3c, 0x31, 0x9f, 0x76, 0x96, 0xa7, 0x32, 0x45, 0x0f, 0x69,
	0xc6, 0xdb, 0x45, 0xb4, 0xad, 0xe1, 0xe0, 0x65, 0x95, 0x36, 0x9b, 0xdf, 0xe8, 0x55, 0x2b, 0xf1,
	0x47, 0x68, 0x10, 0x25, 0x09, 0xa9, 0x5c, 0x2d, 0x50, 0x07, 0x5c, 0xed, 0xe0, 0x5b, 0x2d, 0xeb,
	0xbc, 0xd1, 0x7d, 0xd2, 0xbe, 0xe5, 0xdc, 0xd6, 0x6c, 0x62, 0x68, 0xf8, 0x13, 0xc0, 0x56, 0x4f,
	0xd1, 0x1b, 0xa8, 0x6b, 0x5c, 0xf8, 0x56, 0xcb, 0xb9, 0x4f, 0xbf, 0xe1, 0xe1, 0x00, 0x0e, 0x35,
	0x14, 0x85, 0xe8, 0x04, 0x6c, 0xae, 0x33, 0x7b, 0xc4, 0xe6, 0x09, 0x7e, 0x06, 0xde, 0x26, 0x26,
	0x50, 0x13, 0x1c, 0x6e, 0x7c, 0x3d, 0x52, 0xfc, 0xe2, 0xdf, 0x36, 0xb8, 0x3a, 0x7e, 0x5b, 0x89,
	0xde, 0x83, 0x37, 0xcd, 0xd3, 0xc5, 0x38, 0xfd, 0xc5, 0x96, 0xbe, 0xad, 0x5a, 0x39, 0xbb, 0x53,
	0x8a, 0x8a, 0x86, 0x4c, 0x52, 0x3e, 0x27, 0x3b, 0x3a, 0x7a, 0x07, 0x75, 0x99, 0x6a, 0xa5, 0xf3,
	0x1f, 0xca, 0x0d, 0x19, 0x3d, 0x06, 0x97, 0xad, 0x73, 0x2a, 0x99, 0xff, 0xa0, 0x65, 0x9d, 0x5b,
	0xc4, 0xec, 0xd0, 0x07, 0x00, 0x21, 0xa9, 0x5c, 0x89, 0x5e, 0x9a, 0x30, 0xff, 0xa0, 0x65, 0x9d,
	0x9f, 0x74, 0x4f, 0xef, 0x58, 0x5e, 0x6c, 0x29, 0xa4, 0x44, 0xdf, 0x89, 0xc7, 0x7c, 0xc1, 0x7c,
	0x57, 0xd5, 0x53, 0x25, 0x2e, 0x28, 0xa4, 0x44, 0xc7, 0x7f, 0x2c, 0x68, 0x94, 0x4a, 0x2d, 0x2a,
	0x94, 0xeb, 0x19, 0x15, 0x33, 0x33, 0x29, 0xb3, 0x43, 0x67, 0xe0, 0xc9, 0x82, 0x36, 0xbe, 0xc9,
	0x98, 0x9a, 0x96, 0x47, 0x76, 0x00, 0xf2, 0xa1, 0x4e, 0x93, 0x24, 0x67, 0x42, 0xa8, 0x79, 0x78,
	0x64, 0xb3, 0x45, 0xcf, 0x01, 0x14, 0xed, 0x3b, 0x9d, 0xaf, 0x74, 0xd7, 0x1e, 0x29, 0x21, 0x08,
	0xc3, 0x91, 0xd4, 0xe9, 0x27, 0x7c, 0x41, 0xe7, 0xaa, 0xf7, 0x03, 0xb2, 0x87, 0xe1, 0x35, 0xc0,
	0xae, 0x7a, 0xd4, 0x82, 0x46, 0xc6, 0x96, 0x09, 0x5f, 0x5e, 0xab, 0x7e, 0x8b, 0x32, 0x1d, 0x52,
	0x86, 0x0a, 0xcf, 0x29, 0x5f, 0x72, 0x31, 0x63, 0x89, 0xa2, 0xd8, 0x8a, 0xb2, 0x87, 0xa1, 0x17,
	0x70, 0x3c, 0x49, 0x97, 0x53, 0x9e, 0x2f, 0x0c, 0xc9, 0x51, 0xa4, 0x7d, 0xf0, 0x75, 0x6f, 0x93,
	0x59, 0x0d, 0xfa, 0x18, 0xbc, 0x78, 0x34, 0xfe, 0x39, 0x18, 0x5d, 0xc6, 0x61, 0xb3, 0x86, 0x1a,
	0x50, 0xff, 0xd6, 0x8f, 0xc3, 0x28, 0x1e, 0x36, 0xad, 0x22, 0xd6, 0x1b, 0xc5, 0x83, 0x88, 0x7c,
	0xed, 0x87, 0x4d, 0x1b, 0x01, 0xb8, 0x83, 0x28, 0x8e, 0x2e, 0xbe, 0x34, 0x9d, 0xee, 0x5f, 0x0b,
	0x0e, 0x43, 0x73, 0xcf, 0xd0, 0x00, 0xbc, 0x21, 0x93, 0xe6, 0x48, 0x3e, 0xad, 0x38, 0xfa, 0x51,
	0x18, 0x9c, 0x55, 0x84, 0xd4, 0x1d, 0xc4, 0x35, 0x34, 0x04, 0xd8, 0xfa, 0x08, 0x14, 0x54, 0x1a,
	0x89, 0xe0, 0xb4, 0xda, 0x89, 0xe2, 0x1a, 0xea, 0xc3, 0xd1, 0x65, 0x96, 0x50, 0xc9, 0x4c, 0x4d,
	0xf7, 0x26, 0x0e, 0x1e, 0x95, 0xa3, 0xc5, 0x13, 0x41, 0x8a, 0x15, 0xd7, 0x3e, 0x1f, 0xfe, 0x30,
	0xd7, 0xfd, 0xca, 0x55, 0xaf, 0xc6, 0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x58, 0x6b,
	0x95, 0x9c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatabaseClient is the client API for Database service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabaseClient interface {
	GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*RecordDatum, error)
	GetRecords(ctx context.Context, in *RecordIDs, opts ...grpc.CallOption) (*RecordData, error)
	UpdateRecord(ctx context.Context, in *RecordDatum, opts ...grpc.CallOption) (*reply.Reply, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*RecordDatum, error) {
	out := new(RecordDatum)
	err := c.cc.Invoke(ctx, "/api.grpc.record.Database/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) GetRecords(ctx context.Context, in *RecordIDs, opts ...grpc.CallOption) (*RecordData, error) {
	out := new(RecordData)
	err := c.cc.Invoke(ctx, "/api.grpc.record.Database/GetRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseClient) UpdateRecord(ctx context.Context, in *RecordDatum, opts ...grpc.CallOption) (*reply.Reply, error) {
	out := new(reply.Reply)
	err := c.cc.Invoke(ctx, "/api.grpc.record.Database/UpdateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServer is the server API for Database service.
type DatabaseServer interface {
	GetRecord(context.Context, *RecordID) (*RecordDatum, error)
	GetRecords(context.Context, *RecordIDs) (*RecordData, error)
	UpdateRecord(context.Context, *RecordDatum) (*reply.Reply, error)
}

// UnimplementedDatabaseServer can be embedded to have forward compatible implementations.
type UnimplementedDatabaseServer struct {
}

func (*UnimplementedDatabaseServer) GetRecord(ctx context.Context, req *RecordID) (*RecordDatum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (*UnimplementedDatabaseServer) GetRecords(ctx context.Context, req *RecordIDs) (*RecordData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecords not implemented")
}
func (*UnimplementedDatabaseServer) UpdateRecord(ctx context.Context, req *RecordDatum) (*reply.Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRecord not implemented")
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.grpc.record.Database/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetRecord(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordIDs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.grpc.record.Database/GetRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetRecords(ctx, req.(*RecordIDs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Database_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDatum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.grpc.record.Database/UpdateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).UpdateRecord(ctx, req.(*RecordDatum))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.grpc.record.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _Database_GetRecord_Handler,
		},
		{
			MethodName: "GetRecords",
			Handler:    _Database_GetRecords_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _Database_UpdateRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/database/api/grpc/record/record.proto",
}
