// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/model/record/record.proto

package record

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	token "gitlab.com/packtumi9722/huanhuanhuei/src/database/model/token"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_NOT_FOUND StatusCode = 0
	StatusCode_PENDING   StatusCode = 1
	StatusCode_CONFIRMED StatusCode = 2
	StatusCode_FINISH    StatusCode = 3
	StatusCode_FAIL      StatusCode = 4
)

var StatusCode_name = map[int32]string{
	0: "NOT_FOUND",
	1: "PENDING",
	2: "CONFIRMED",
	3: "FINISH",
	4: "FAIL",
}

var StatusCode_value = map[string]int32{
	"NOT_FOUND": 0,
	"PENDING":   1,
	"CONFIRMED": 2,
	"FINISH":    3,
	"FAIL":      4,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07d19669ba121833, []int{0}
}

type Record struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromToken            *TokenDetail `protobuf:"bytes,2,opt,name=fromToken,proto3" json:"fromToken,omitempty"`
	ToToken              *TokenDetail `protobuf:"bytes,3,opt,name=toToken,proto3" json:"toToken,omitempty"`
	Exrate               float64      `protobuf:"fixed64,4,opt,name=exrate,proto3" json:"exrate,omitempty"`
	StatusCode           StatusCode   `protobuf:"varint,5,opt,name=statusCode,proto3,enum=model.record.StatusCode" json:"statusCode,omitempty"`
	StatusTime           *StatusTime  `protobuf:"bytes,6,opt,name=statusTime,proto3" json:"statusTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_07d19669ba121833, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetFromToken() *TokenDetail {
	if m != nil {
		return m.FromToken
	}
	return nil
}

func (m *Record) GetToToken() *TokenDetail {
	if m != nil {
		return m.ToToken
	}
	return nil
}

func (m *Record) GetExrate() float64 {
	if m != nil {
		return m.Exrate
	}
	return 0
}

func (m *Record) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_NOT_FOUND
}

func (m *Record) GetStatusTime() *StatusTime {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type TokenDetail struct {
	Txhash               string          `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	TokenType            token.TokenType `protobuf:"varint,2,opt,name=tokenType,proto3,enum=model.token.TokenType" json:"tokenType,omitempty"`
	Address              string          `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TokenValue           string          `protobuf:"bytes,4,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	TokenDecimal         int32           `protobuf:"varint,5,opt,name=tokenDecimal,proto3" json:"tokenDecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TokenDetail) Reset()         { *m = TokenDetail{} }
func (m *TokenDetail) String() string { return proto.CompactTextString(m) }
func (*TokenDetail) ProtoMessage()    {}
func (*TokenDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_07d19669ba121833, []int{1}
}

func (m *TokenDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDetail.Unmarshal(m, b)
}
func (m *TokenDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDetail.Marshal(b, m, deterministic)
}
func (m *TokenDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDetail.Merge(m, src)
}
func (m *TokenDetail) XXX_Size() int {
	return xxx_messageInfo_TokenDetail.Size(m)
}
func (m *TokenDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDetail proto.InternalMessageInfo

func (m *TokenDetail) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *TokenDetail) GetTokenType() token.TokenType {
	if m != nil {
		return m.TokenType
	}
	return token.TokenType_BTC
}

func (m *TokenDetail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenDetail) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *TokenDetail) GetTokenDecimal() int32 {
	if m != nil {
		return m.TokenDecimal
	}
	return 0
}

type StatusTime struct {
	PendingTime          int64    `protobuf:"varint,1,opt,name=pendingTime,proto3" json:"pendingTime,omitempty"`
	FinishedTime         int64    `protobuf:"varint,2,opt,name=finishedTime,proto3" json:"finishedTime,omitempty"`
	ConfirmedTime        int64    `protobuf:"varint,3,opt,name=confirmedTime,proto3" json:"confirmedTime,omitempty"`
	FailedTime           int64    `protobuf:"varint,4,opt,name=failedTime,proto3" json:"failedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusTime) Reset()         { *m = StatusTime{} }
func (m *StatusTime) String() string { return proto.CompactTextString(m) }
func (*StatusTime) ProtoMessage()    {}
func (*StatusTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_07d19669ba121833, []int{2}
}

func (m *StatusTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusTime.Unmarshal(m, b)
}
func (m *StatusTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusTime.Marshal(b, m, deterministic)
}
func (m *StatusTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusTime.Merge(m, src)
}
func (m *StatusTime) XXX_Size() int {
	return xxx_messageInfo_StatusTime.Size(m)
}
func (m *StatusTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusTime.DiscardUnknown(m)
}

var xxx_messageInfo_StatusTime proto.InternalMessageInfo

func (m *StatusTime) GetPendingTime() int64 {
	if m != nil {
		return m.PendingTime
	}
	return 0
}

func (m *StatusTime) GetFinishedTime() int64 {
	if m != nil {
		return m.FinishedTime
	}
	return 0
}

func (m *StatusTime) GetConfirmedTime() int64 {
	if m != nil {
		return m.ConfirmedTime
	}
	return 0
}

func (m *StatusTime) GetFailedTime() int64 {
	if m != nil {
		return m.FailedTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("model.record.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Record)(nil), "model.record.Record")
	proto.RegisterType((*TokenDetail)(nil), "model.record.TokenDetail")
	proto.RegisterType((*StatusTime)(nil), "model.record.StatusTime")
}

func init() {
	proto.RegisterFile("src/database/model/record/record.proto", fileDescriptor_07d19669ba121833)
}

var fileDescriptor_07d19669ba121833 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x71, 0xda, 0xa5, 0xcb, 0xbf, 0x5b, 0x15, 0xf9, 0x30, 0x05, 0x0e, 0x28, 0xaa, 0x26,
	0x54, 0x71, 0x68, 0xa5, 0x0e, 0x09, 0xae, 0xb0, 0xae, 0x10, 0x89, 0xa5, 0xc8, 0x0b, 0x1c, 0xb8,
	0x20, 0xaf, 0x76, 0xa9, 0x45, 0x12, 0x57, 0xb1, 0x27, 0x8d, 0xaf, 0xc1, 0x89, 0xaf, 0xc2, 0xb7,
	0x43, 0xf9, 0x3b, 0xa5, 0x89, 0x54, 0x89, 0x4b, 0x22, 0xbf, 0xff, 0xef, 0xd9, 0x2f, 0xcf, 0x81,
	0x17, 0xa6, 0x5a, 0xcf, 0x04, 0xb7, 0xfc, 0x9e, 0x1b, 0x39, 0x2b, 0xb4, 0x90, 0xf9, 0xac, 0x92,
	0x6b, 0x5d, 0x89, 0xe6, 0x35, 0xdd, 0x55, 0xda, 0x6a, 0x7a, 0x86, 0xa3, 0xa9, 0xd3, 0x9e, 0x5d,
	0x1e, 0x71, 0x59, 0xfd, 0x43, 0x96, 0xee, 0xe9, 0x3c, 0xe3, 0x5f, 0x1e, 0xf8, 0x0c, 0x0d, 0x74,
	0x04, 0x9e, 0x12, 0x11, 0x89, 0xc9, 0x24, 0x60, 0x9e, 0x12, 0xf4, 0x35, 0x04, 0x9b, 0x4a, 0x17,
	0x59, 0x4d, 0x47, 0x5e, 0x4c, 0x26, 0xc3, 0xf9, 0xd3, 0x69, 0xfb, 0x88, 0x29, 0x8e, 0x16, 0xd2,
	0x72, 0x95, 0xb3, 0x03, 0x4b, 0xaf, 0x60, 0x60, 0xb5, 0xb3, 0xf5, 0xfe, 0x67, 0xdb, 0x93, 0xf4,
	0x02, 0x7c, 0xf9, 0x58, 0x71, 0x2b, 0xa3, 0x7e, 0x4c, 0x26, 0x84, 0x35, 0x2b, 0xfa, 0x06, 0xc0,
	0x58, 0x6e, 0x1f, 0xcc, 0xb5, 0x16, 0x32, 0x3a, 0x89, 0xc9, 0x64, 0x34, 0x8f, 0xba, 0xfb, 0xdd,
	0xfd, 0x9b, 0xb3, 0x16, 0x7b, 0x70, 0x66, 0xaa, 0x90, 0x91, 0x8f, 0x49, 0x8e, 0x3a, 0xeb, 0x39,
	0x6b, 0xb1, 0xe3, 0x3f, 0x04, 0x86, 0xad, 0x90, 0x75, 0x36, 0xfb, 0xb8, 0xe5, 0x66, 0xdb, 0xb4,
	0xd3, 0xac, 0xe8, 0x2b, 0x08, 0xb0, 0xcb, 0xec, 0xe7, 0x4e, 0x62, 0x43, 0xa3, 0xf9, 0x45, 0x73,
	0x80, 0xeb, 0x38, 0xdb, 0x4f, 0xd9, 0x01, 0xa4, 0x11, 0x0c, 0xb8, 0x10, 0x95, 0x34, 0x06, 0xeb,
	0x09, 0xd8, 0x7e, 0x49, 0x9f, 0x03, 0x20, 0xf6, 0x85, 0xe7, 0x0f, 0xae, 0x87, 0x80, 0xb5, 0x14,
	0x3a, 0x86, 0x33, 0xeb, 0x62, 0xad, 0x55, 0xc1, 0x73, 0x6c, 0xe3, 0x84, 0x75, 0xb4, 0xf1, 0x6f,
	0x02, 0x70, 0xf8, 0x2c, 0x1a, 0xc3, 0x70, 0x27, 0x4b, 0xa1, 0xca, 0xef, 0xd8, 0x42, 0x9d, 0xbf,
	0xc7, 0xda, 0x52, 0xbd, 0xe9, 0x46, 0x95, 0xca, 0x6c, 0xa5, 0x40, 0xc4, 0x43, 0xa4, 0xa3, 0xd1,
	0x4b, 0x38, 0x5f, 0xeb, 0x72, 0xa3, 0xaa, 0xa2, 0x81, 0x7a, 0x08, 0x75, 0xc5, 0x3a, 0xfe, 0x86,
	0xab, 0xbc, 0x41, 0xfa, 0x88, 0xb4, 0x94, 0x97, 0xb7, 0xfb, 0x64, 0x78, 0x3d, 0xe7, 0x10, 0xa4,
	0xab, 0xec, 0xdb, 0x72, 0xf5, 0x39, 0x5d, 0x84, 0x4f, 0xe8, 0x10, 0x06, 0x9f, 0x6e, 0xd2, 0x45,
	0x92, 0xbe, 0x0f, 0x49, 0x3d, 0xbb, 0x5e, 0xa5, 0xcb, 0x84, 0xdd, 0xde, 0x2c, 0x42, 0x8f, 0x02,
	0xf8, 0xcb, 0x24, 0x4d, 0xee, 0x3e, 0x84, 0x3d, 0x7a, 0x0a, 0xfd, 0xe5, 0xdb, 0xe4, 0x63, 0xd8,
	0x7f, 0x77, 0xfa, 0xd5, 0x77, 0xd7, 0x78, 0xef, 0xe3, 0xbf, 0x7c, 0xf5, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x8a, 0x0e, 0xd7, 0x29, 0x03, 0x00, 0x00,
}
