// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/model/pending/pending.proto

package pending

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pending struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PendingTime          int64    `protobuf:"varint,2,opt,name=pendingTime,proto3" json:"pendingTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pending) Reset()         { *m = Pending{} }
func (m *Pending) String() string { return proto.CompactTextString(m) }
func (*Pending) ProtoMessage()    {}
func (*Pending) Descriptor() ([]byte, []int) {
	return fileDescriptor_d165c95c79ee46aa, []int{0}
}

func (m *Pending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pending.Unmarshal(m, b)
}
func (m *Pending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pending.Marshal(b, m, deterministic)
}
func (m *Pending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pending.Merge(m, src)
}
func (m *Pending) XXX_Size() int {
	return xxx_messageInfo_Pending.Size(m)
}
func (m *Pending) XXX_DiscardUnknown() {
	xxx_messageInfo_Pending.DiscardUnknown(m)
}

var xxx_messageInfo_Pending proto.InternalMessageInfo

func (m *Pending) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pending) GetPendingTime() int64 {
	if m != nil {
		return m.PendingTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Pending)(nil), "model.pending.Pending")
}

func init() {
	proto.RegisterFile("src/database/model/pending/pending.proto", fileDescriptor_d165c95c79ee46aa)
}

var fileDescriptor_d165c95c79ee46aa = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x2e, 0x4a, 0xd6,
	0x4f, 0x49, 0x2c, 0x49, 0x4c, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x2f,
	0x48, 0xcd, 0x4b, 0xc9, 0xcc, 0x4b, 0x87, 0xd1, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xbc,
	0x60, 0x49, 0x3d, 0xa8, 0xa0, 0x92, 0x35, 0x17, 0x7b, 0x00, 0x84, 0x29, 0xc4, 0xc7, 0xc5, 0x94,
	0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0x22, 0xa4, 0xc0, 0xc5, 0x0d,
	0x55, 0x15, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x2c, 0xe4, 0xc4,
	0x19, 0xc5, 0x0e, 0xe5, 0x26, 0xb1, 0x81, 0x4d, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x7a, 0x1f, 0x8f, 0x89, 0x00, 0x00, 0x00,
}
