// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DBReply struct {
	Reply                *Record  `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBReply) Reset()         { *m = DBReply{} }
func (m *DBReply) String() string { return proto.CompactTextString(m) }
func (*DBReply) ProtoMessage()    {}
func (*DBReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *DBReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBReply.Unmarshal(m, b)
}
func (m *DBReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBReply.Marshal(b, m, deterministic)
}
func (m *DBReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBReply.Merge(m, src)
}
func (m *DBReply) XXX_Size() int {
	return xxx_messageInfo_DBReply.Size(m)
}
func (m *DBReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DBReply.DiscardUnknown(m)
}

var xxx_messageInfo_DBReply proto.InternalMessageInfo

func (m *DBReply) GetReply() *Record {
	if m != nil {
		return m.Reply
	}
	return nil
}

type DBReplies struct {
	Replies              []*Record `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DBReplies) Reset()         { *m = DBReplies{} }
func (m *DBReplies) String() string { return proto.CompactTextString(m) }
func (*DBReplies) ProtoMessage()    {}
func (*DBReplies) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *DBReplies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBReplies.Unmarshal(m, b)
}
func (m *DBReplies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBReplies.Marshal(b, m, deterministic)
}
func (m *DBReplies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBReplies.Merge(m, src)
}
func (m *DBReplies) XXX_Size() int {
	return xxx_messageInfo_DBReplies.Size(m)
}
func (m *DBReplies) XXX_DiscardUnknown() {
	xxx_messageInfo_DBReplies.DiscardUnknown(m)
}

var xxx_messageInfo_DBReplies proto.InternalMessageInfo

func (m *DBReplies) GetReplies() []*Record {
	if m != nil {
		return m.Replies
	}
	return nil
}

type DBRequest struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBRequest) Reset()         { *m = DBRequest{} }
func (m *DBRequest) String() string { return proto.CompactTextString(m) }
func (*DBRequest) ProtoMessage()    {}
func (*DBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{2}
}

func (m *DBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequest.Unmarshal(m, b)
}
func (m *DBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequest.Marshal(b, m, deterministic)
}
func (m *DBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequest.Merge(m, src)
}
func (m *DBRequest) XXX_Size() int {
	return xxx_messageInfo_DBRequest.Size(m)
}
func (m *DBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequest proto.InternalMessageInfo

func (m *DBRequest) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type DBRequests struct {
	Txhashes             []string `protobuf:"bytes,1,rep,name=txhashes,proto3" json:"txhashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBRequests) Reset()         { *m = DBRequests{} }
func (m *DBRequests) String() string { return proto.CompactTextString(m) }
func (*DBRequests) ProtoMessage()    {}
func (*DBRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{3}
}

func (m *DBRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBRequests.Unmarshal(m, b)
}
func (m *DBRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBRequests.Marshal(b, m, deterministic)
}
func (m *DBRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBRequests.Merge(m, src)
}
func (m *DBRequests) XXX_Size() int {
	return xxx_messageInfo_DBRequests.Size(m)
}
func (m *DBRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_DBRequests.DiscardUnknown(m)
}

var xxx_messageInfo_DBRequests proto.InternalMessageInfo

func (m *DBRequests) GetTxhashes() []string {
	if m != nil {
		return m.Txhashes
	}
	return nil
}

type Record struct {
	Txhash               string       `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	FromToken            *TokenDetail `protobuf:"bytes,2,opt,name=fromToken,proto3" json:"fromToken,omitempty"`
	ToToken              *TokenDetail `protobuf:"bytes,3,opt,name=toToken,proto3" json:"toToken,omitempty"`
	Exrate               float64      `protobuf:"fixed64,4,opt,name=exrate,proto3" json:"exrate,omitempty"`
	StatusCode           int32        `protobuf:"varint,5,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusTime           *StatusTime  `protobuf:"bytes,6,opt,name=statusTime,proto3" json:"statusTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{4}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *Record) GetFromToken() *TokenDetail {
	if m != nil {
		return m.FromToken
	}
	return nil
}

func (m *Record) GetToToken() *TokenDetail {
	if m != nil {
		return m.ToToken
	}
	return nil
}

func (m *Record) GetExrate() float64 {
	if m != nil {
		return m.Exrate
	}
	return 0
}

func (m *Record) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Record) GetStatusTime() *StatusTime {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type TokenDetail struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TokenValue           string   `protobuf:"bytes,4,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	TokenDecimal         int32    `protobuf:"varint,5,opt,name=tokenDecimal,proto3" json:"tokenDecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenDetail) Reset()         { *m = TokenDetail{} }
func (m *TokenDetail) String() string { return proto.CompactTextString(m) }
func (*TokenDetail) ProtoMessage()    {}
func (*TokenDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{5}
}

func (m *TokenDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDetail.Unmarshal(m, b)
}
func (m *TokenDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDetail.Marshal(b, m, deterministic)
}
func (m *TokenDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDetail.Merge(m, src)
}
func (m *TokenDetail) XXX_Size() int {
	return xxx_messageInfo_TokenDetail.Size(m)
}
func (m *TokenDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDetail proto.InternalMessageInfo

func (m *TokenDetail) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *TokenDetail) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *TokenDetail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenDetail) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *TokenDetail) GetTokenDecimal() int32 {
	if m != nil {
		return m.TokenDecimal
	}
	return 0
}

type StatusTime struct {
	PendingAt            int64    `protobuf:"varint,1,opt,name=pendingAt,proto3" json:"pendingAt,omitempty"`
	FinishedAt           int64    `protobuf:"varint,2,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	ConfirmedAt          int64    `protobuf:"varint,3,opt,name=confirmedAt,proto3" json:"confirmedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusTime) Reset()         { *m = StatusTime{} }
func (m *StatusTime) String() string { return proto.CompactTextString(m) }
func (*StatusTime) ProtoMessage()    {}
func (*StatusTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{6}
}

func (m *StatusTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusTime.Unmarshal(m, b)
}
func (m *StatusTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusTime.Marshal(b, m, deterministic)
}
func (m *StatusTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusTime.Merge(m, src)
}
func (m *StatusTime) XXX_Size() int {
	return xxx_messageInfo_StatusTime.Size(m)
}
func (m *StatusTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusTime.DiscardUnknown(m)
}

var xxx_messageInfo_StatusTime proto.InternalMessageInfo

func (m *StatusTime) GetPendingAt() int64 {
	if m != nil {
		return m.PendingAt
	}
	return 0
}

func (m *StatusTime) GetFinishedAt() int64 {
	if m != nil {
		return m.FinishedAt
	}
	return 0
}

func (m *StatusTime) GetConfirmedAt() int64 {
	if m != nil {
		return m.ConfirmedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*DBReply)(nil), "database.DBReply")
	proto.RegisterType((*DBReplies)(nil), "database.DBReplies")
	proto.RegisterType((*DBRequest)(nil), "database.DBRequest")
	proto.RegisterType((*DBRequests)(nil), "database.DBRequests")
	proto.RegisterType((*Record)(nil), "database.Record")
	proto.RegisterType((*TokenDetail)(nil), "database.TokenDetail")
	proto.RegisterType((*StatusTime)(nil), "database.StatusTime")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x14, 0xac, 0x59, 0x92, 0x8d, 0x5f, 0x7a, 0x00, 0xb7, 0xa0, 0x55, 0x84, 0xd0, 0xca, 0x48, 0x28,
	0xe2, 0x10, 0x44, 0x0b, 0x42, 0x1c, 0x5b, 0x22, 0x71, 0x37, 0x11, 0x07, 0x6e, 0x6e, 0xf6, 0x85,
	0x58, 0x6c, 0xd6, 0x8b, 0xed, 0x48, 0x8d, 0xc4, 0x9f, 0xe1, 0x3f, 0xf2, 0x03, 0x90, 0xed, 0xfd,
	0x2a, 0x6a, 0x7a, 0xdb, 0x37, 0x9e, 0xf1, 0xcc, 0x58, 0x6f, 0xe1, 0xd4, 0xe0, 0x5a, 0x9b, 0x62,
	0x51, 0x1b, 0xed, 0x34, 0x9b, 0x14, 0xd2, 0xc9, 0x1b, 0x69, 0x91, 0xbf, 0x83, 0x74, 0x79, 0x2d,
	0xb0, 0x2e, 0x0f, 0xec, 0x35, 0x8c, 0x8c, 0xff, 0xc8, 0x48, 0x4e, 0xe6, 0xd3, 0x8b, 0x27, 0x8b,
	0x96, 0xb4, 0x10, 0x41, 0x2b, 0xe2, 0x31, 0xff, 0x08, 0x34, 0x4a, 0x14, 0x5a, 0xf6, 0x06, 0x52,
	0x13, 0x3f, 0x33, 0x92, 0x27, 0xf7, 0xca, 0x5a, 0x02, 0x7f, 0x15, 0x85, 0xbf, 0xf6, 0x68, 0x1d,
	0x7b, 0x0e, 0x63, 0x77, 0xbb, 0x95, 0x76, 0x1b, 0xec, 0xa8, 0x68, 0x26, 0x3e, 0x07, 0xe8, 0x48,
	0x96, 0xcd, 0x60, 0x12, 0xf1, 0xe6, 0x7e, 0x2a, 0xba, 0x99, 0xff, 0x25, 0x30, 0x8e, 0x16, 0xc7,
	0x2e, 0x63, 0x97, 0x40, 0x37, 0x46, 0xef, 0x56, 0xfa, 0x27, 0x56, 0xd9, 0xa3, 0x50, 0xeb, 0x59,
	0x9f, 0x2f, 0xc0, 0x4b, 0x74, 0x52, 0x95, 0xa2, 0xe7, 0xb1, 0xb7, 0x90, 0x3a, 0x1d, 0x25, 0xc9,
	0x43, 0x92, 0x96, 0xe5, 0xdd, 0xf1, 0xd6, 0x48, 0x87, 0xd9, 0xe3, 0x9c, 0xcc, 0x89, 0x68, 0x26,
	0xf6, 0x12, 0xc0, 0x3a, 0xe9, 0xf6, 0xf6, 0xb3, 0x2e, 0x30, 0x1b, 0xe5, 0x64, 0x3e, 0x12, 0x03,
	0x84, 0xbd, 0x6f, 0xcf, 0x57, 0x6a, 0x87, 0xd9, 0x38, 0x78, 0x9d, 0xf7, 0x5e, 0x5f, 0xbb, 0x33,
	0x31, 0xe0, 0xf1, 0x3f, 0x04, 0xa6, 0x83, 0x18, 0x47, 0xbb, 0xbf, 0x00, 0xea, 0x3c, 0x6d, 0x75,
	0xa8, 0x31, 0x74, 0xa7, 0xa2, 0x07, 0x58, 0x06, 0xa9, 0x2c, 0x0a, 0x83, 0xd6, 0x86, 0x92, 0x54,
	0xb4, 0xa3, 0x4f, 0x1d, 0x68, 0xdf, 0x64, 0xb9, 0x8f, 0x8d, 0xa8, 0x18, 0x20, 0x8c, 0xc3, 0xa9,
	0x8b, 0xf6, 0x6b, 0xb5, 0x93, 0x65, 0xd3, 0xeb, 0x0e, 0xc6, 0x4b, 0x80, 0x3e, 0xbd, 0x4f, 0x52,
	0x63, 0x55, 0xa8, 0xea, 0xc7, 0x95, 0x0b, 0x21, 0x13, 0xd1, 0x03, 0xde, 0x6f, 0xa3, 0x2a, 0x65,
	0xb7, 0x58, 0x5c, 0xb9, 0x10, 0x34, 0x11, 0x03, 0x84, 0xe5, 0x30, 0x5d, 0xeb, 0x6a, 0xa3, 0xcc,
	0x2e, 0x10, 0x92, 0x40, 0x18, 0x42, 0x17, 0xbf, 0x61, 0xb2, 0x6c, 0x1e, 0x8d, 0x7d, 0x00, 0xfa,
	0x05, 0x5d, 0xb3, 0x16, 0x67, 0xfd, 0x63, 0x76, 0x3b, 0x35, 0x7b, 0x7a, 0x17, 0xf4, 0x1b, 0x7d,
	0xc2, 0x3e, 0x01, 0x74, 0x32, 0xcb, 0xce, 0xef, 0xd1, 0xd9, 0xd9, 0xd9, 0xff, 0x42, 0xbf, 0xd3,
	0x27, 0xd7, 0xe9, 0xf7, 0x91, 0x3b, 0xd4, 0x68, 0x6f, 0xc6, 0xe1, 0xdf, 0xba, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xad, 0xfd, 0xd0, 0xb5, 0x6b, 0x03, 0x00, 0x00,
}
