// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/types/pending/pending.proto

package pending

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
	_ "src/database/types/reply"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PendingItem struct {
	Item                 *Pending `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingItem) Reset()         { *m = PendingItem{} }
func (m *PendingItem) String() string { return proto.CompactTextString(m) }
func (*PendingItem) ProtoMessage()    {}
func (*PendingItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1897aa120629ba64, []int{0}
}

func (m *PendingItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingItem.Unmarshal(m, b)
}
func (m *PendingItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingItem.Marshal(b, m, deterministic)
}
func (m *PendingItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingItem.Merge(m, src)
}
func (m *PendingItem) XXX_Size() int {
	return xxx_messageInfo_PendingItem.Size(m)
}
func (m *PendingItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingItem.DiscardUnknown(m)
}

var xxx_messageInfo_PendingItem proto.InternalMessageInfo

func (m *PendingItem) GetItem() *Pending {
	if m != nil {
		return m.Item
	}
	return nil
}

type PendingItems struct {
	Items                []*Pending `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PendingItems) Reset()         { *m = PendingItems{} }
func (m *PendingItems) String() string { return proto.CompactTextString(m) }
func (*PendingItems) ProtoMessage()    {}
func (*PendingItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_1897aa120629ba64, []int{1}
}

func (m *PendingItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingItems.Unmarshal(m, b)
}
func (m *PendingItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingItems.Marshal(b, m, deterministic)
}
func (m *PendingItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingItems.Merge(m, src)
}
func (m *PendingItems) XXX_Size() int {
	return xxx_messageInfo_PendingItems.Size(m)
}
func (m *PendingItems) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingItems.DiscardUnknown(m)
}

var xxx_messageInfo_PendingItems proto.InternalMessageInfo

func (m *PendingItems) GetItems() []*Pending {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemID) Reset()         { *m = ItemID{} }
func (m *ItemID) String() string { return proto.CompactTextString(m) }
func (*ItemID) ProtoMessage()    {}
func (*ItemID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1897aa120629ba64, []int{2}
}

func (m *ItemID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemID.Unmarshal(m, b)
}
func (m *ItemID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemID.Marshal(b, m, deterministic)
}
func (m *ItemID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemID.Merge(m, src)
}
func (m *ItemID) XXX_Size() int {
	return xxx_messageInfo_ItemID.Size(m)
}
func (m *ItemID) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemID.DiscardUnknown(m)
}

var xxx_messageInfo_ItemID proto.InternalMessageInfo

func (m *ItemID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Pending struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PendingTime          int64    `protobuf:"varint,2,opt,name=pendingTime,proto3" json:"pendingTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pending) Reset()         { *m = Pending{} }
func (m *Pending) String() string { return proto.CompactTextString(m) }
func (*Pending) ProtoMessage()    {}
func (*Pending) Descriptor() ([]byte, []int) {
	return fileDescriptor_1897aa120629ba64, []int{3}
}

func (m *Pending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pending.Unmarshal(m, b)
}
func (m *Pending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pending.Marshal(b, m, deterministic)
}
func (m *Pending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pending.Merge(m, src)
}
func (m *Pending) XXX_Size() int {
	return xxx_messageInfo_Pending.Size(m)
}
func (m *Pending) XXX_DiscardUnknown() {
	xxx_messageInfo_Pending.DiscardUnknown(m)
}

var xxx_messageInfo_Pending proto.InternalMessageInfo

func (m *Pending) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pending) GetPendingTime() int64 {
	if m != nil {
		return m.PendingTime
	}
	return 0
}

func init() {
	proto.RegisterType((*PendingItem)(nil), "database.types.pending.PendingItem")
	proto.RegisterType((*PendingItems)(nil), "database.types.pending.PendingItems")
	proto.RegisterType((*ItemID)(nil), "database.types.pending.ItemID")
	proto.RegisterType((*Pending)(nil), "database.types.pending.Pending")
}

func init() {
	proto.RegisterFile("src/database/types/pending/pending.proto", fileDescriptor_1897aa120629ba64)
}

var fileDescriptor_1897aa120629ba64 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x6b, 0xc2, 0x30,
	0x14, 0xc7, 0xad, 0x6e, 0x3a, 0x5f, 0xe7, 0x0e, 0x81, 0x49, 0xe9, 0x61, 0x2b, 0x9d, 0x07, 0x4f,
	0x29, 0x28, 0x3b, 0xed, 0x26, 0xca, 0xe6, 0x41, 0x18, 0x65, 0xbb, 0xec, 0x56, 0xcd, 0x9b, 0x04,
	0xfa, 0x23, 0x34, 0x71, 0xd0, 0x7f, 0x7b, 0x7f, 0xc1, 0x68, 0x92, 0xa2, 0x88, 0x32, 0x2f, 0x2d,
	0xbc, 0x7c, 0xde, 0x27, 0xdf, 0xf7, 0x02, 0x63, 0x59, 0x6e, 0x22, 0x96, 0xa8, 0x64, 0x9d, 0x48,
	0x8c, 0x54, 0x25, 0x50, 0x46, 0x02, 0x73, 0xc6, 0xf3, 0x6d, 0xf3, 0xa7, 0xa2, 0x2c, 0x54, 0x41,
	0x86, 0x0d, 0x45, 0x35, 0x45, 0xed, 0xa9, 0x3f, 0xfd, 0xc1, 0x9c, 0x15, 0x65, 0xa4, 0xa9, 0xf5,
	0xee, 0x3b, 0xe2, 0xf9, 0x26, 0xdd, 0x31, 0x8c, 0xb6, 0x45, 0xb1, 0x4d, 0x71, 0x5f, 0xc7, 0x4c,
	0xa8, 0xca, 0xc8, 0xfc, 0xd1, 0x89, 0x6b, 0x4b, 0x14, 0x69, 0x65, 0xbe, 0x86, 0x0a, 0x67, 0xe0,
	0xbe, 0x9b, 0x5b, 0x96, 0x0a, 0x33, 0x32, 0x85, 0x2b, 0xae, 0x30, 0xf3, 0x9c, 0xc0, 0x19, 0xbb,
	0x93, 0x47, 0x7a, 0x3a, 0x10, 0xb5, 0x2d, 0xb1, 0x86, 0xc3, 0x05, 0xdc, 0x1e, 0x38, 0x24, 0x79,
	0x86, 0xeb, 0xba, 0x2e, 0x3d, 0x27, 0xe8, 0x5c, 0x62, 0x31, 0x74, 0xe8, 0x41, 0xb7, 0xee, 0x5f,
	0xce, 0xc9, 0x1d, 0xb4, 0x39, 0xd3, 0x19, 0xfa, 0x71, 0x9b, 0xb3, 0xf0, 0x05, 0x7a, 0x96, 0x3d,
	0x3e, 0x22, 0x01, 0xb8, 0x56, 0xf7, 0xc1, 0x33, 0xf4, 0xda, 0x81, 0x33, 0xee, 0xc4, 0x87, 0xa5,
	0xc9, 0xaf, 0x03, 0x37, 0x73, 0x1b, 0x80, 0xac, 0xc0, 0x7d, 0x45, 0x65, 0x65, 0x92, 0x0c, 0xa9,
	0xd9, 0x20, 0x6d, 0x36, 0x48, 0x17, 0xf5, 0x06, 0xfd, 0xd1, 0x3f, 0x91, 0xf5, 0x9c, 0x61, 0x8b,
	0xac, 0x60, 0xf0, 0x29, 0x58, 0xa2, 0xb0, 0x89, 0xf7, 0x74, 0x41, 0xa3, 0x7f, 0x7f, 0x0c, 0xc5,
	0xf5, 0x83, 0x84, 0x2d, 0xf2, 0x06, 0x83, 0x39, 0xa6, 0xb8, 0xd7, 0x3d, 0x9c, 0xd3, 0x99, 0x45,
	0x9d, 0x35, 0xcd, 0xfa, 0x5f, 0x3d, 0x8b, 0xae, 0xbb, 0x7a, 0xb6, 0xe9, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xef, 0x54, 0xeb, 0xf5, 0x87, 0x02, 0x00, 0x00,
}
