// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/huanhuancore/model/btc.proto

package token

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BTC struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Locktime             int64    `protobuf:"varint,2,opt,name=locktime,proto3" json:"locktime,omitempty"`
	Blockhash            string   `protobuf:"bytes,3,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	Confirmations        int64    `protobuf:"varint,4,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	Vin                  []*Vin   `protobuf:"bytes,5,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout                 []*Vout  `protobuf:"bytes,6,rep,name=vout,proto3" json:"vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BTC) Reset()         { *m = BTC{} }
func (m *BTC) String() string { return proto.CompactTextString(m) }
func (*BTC) ProtoMessage()    {}
func (*BTC) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91c898ab8de7d70, []int{0}
}

func (m *BTC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BTC.Unmarshal(m, b)
}
func (m *BTC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BTC.Marshal(b, m, deterministic)
}
func (m *BTC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BTC.Merge(m, src)
}
func (m *BTC) XXX_Size() int {
	return xxx_messageInfo_BTC.Size(m)
}
func (m *BTC) XXX_DiscardUnknown() {
	xxx_messageInfo_BTC.DiscardUnknown(m)
}

var xxx_messageInfo_BTC proto.InternalMessageInfo

func (m *BTC) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *BTC) GetLocktime() int64 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *BTC) GetBlockhash() string {
	if m != nil {
		return m.Blockhash
	}
	return ""
}

func (m *BTC) GetConfirmations() int64 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *BTC) GetVin() []*Vin {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *BTC) GetVout() []*Vout {
	if m != nil {
		return m.Vout
	}
	return nil
}

type Vout struct {
	Value                float64       `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	ScriptPubKey         *ScriptPubKey `protobuf:"bytes,2,opt,name=scriptPubKey,proto3" json:"scriptPubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Vout) Reset()         { *m = Vout{} }
func (m *Vout) String() string { return proto.CompactTextString(m) }
func (*Vout) ProtoMessage()    {}
func (*Vout) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91c898ab8de7d70, []int{1}
}

func (m *Vout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vout.Unmarshal(m, b)
}
func (m *Vout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vout.Marshal(b, m, deterministic)
}
func (m *Vout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vout.Merge(m, src)
}
func (m *Vout) XXX_Size() int {
	return xxx_messageInfo_Vout.Size(m)
}
func (m *Vout) XXX_DiscardUnknown() {
	xxx_messageInfo_Vout.DiscardUnknown(m)
}

var xxx_messageInfo_Vout proto.InternalMessageInfo

func (m *Vout) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Vout) GetScriptPubKey() *ScriptPubKey {
	if m != nil {
		return m.ScriptPubKey
	}
	return nil
}

type ScriptPubKey struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScriptPubKey) Reset()         { *m = ScriptPubKey{} }
func (m *ScriptPubKey) String() string { return proto.CompactTextString(m) }
func (*ScriptPubKey) ProtoMessage()    {}
func (*ScriptPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91c898ab8de7d70, []int{2}
}

func (m *ScriptPubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScriptPubKey.Unmarshal(m, b)
}
func (m *ScriptPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScriptPubKey.Marshal(b, m, deterministic)
}
func (m *ScriptPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScriptPubKey.Merge(m, src)
}
func (m *ScriptPubKey) XXX_Size() int {
	return xxx_messageInfo_ScriptPubKey.Size(m)
}
func (m *ScriptPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ScriptPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_ScriptPubKey proto.InternalMessageInfo

func (m *ScriptPubKey) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type Vin struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 int64    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vin) Reset()         { *m = Vin{} }
func (m *Vin) String() string { return proto.CompactTextString(m) }
func (*Vin) ProtoMessage()    {}
func (*Vin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f91c898ab8de7d70, []int{3}
}

func (m *Vin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vin.Unmarshal(m, b)
}
func (m *Vin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vin.Marshal(b, m, deterministic)
}
func (m *Vin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vin.Merge(m, src)
}
func (m *Vin) XXX_Size() int {
	return xxx_messageInfo_Vin.Size(m)
}
func (m *Vin) XXX_DiscardUnknown() {
	xxx_messageInfo_Vin.DiscardUnknown(m)
}

var xxx_messageInfo_Vin proto.InternalMessageInfo

func (m *Vin) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Vin) GetVout() int64 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func init() {
	proto.RegisterType((*BTC)(nil), "model.token.BTC")
	proto.RegisterType((*Vout)(nil), "model.token.Vout")
	proto.RegisterType((*ScriptPubKey)(nil), "model.token.ScriptPubKey")
	proto.RegisterType((*Vin)(nil), "model.token.Vin")
}

func init() { proto.RegisterFile("src/huanhuancore/model/btc.proto", fileDescriptor_f91c898ab8de7d70) }

var fileDescriptor_f91c898ab8de7d70 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xf4, 0x30,
	0x10, 0x26, 0x6f, 0xba, 0xfb, 0xba, 0xd3, 0x15, 0x34, 0x78, 0x88, 0xe2, 0xa1, 0x14, 0x85, 0x1e,
	0xb4, 0x85, 0xf5, 0xec, 0x65, 0x3d, 0x7a, 0x91, 0x28, 0x7b, 0xd0, 0x53, 0x9b, 0x46, 0x1a, 0xb6,
	0x4d, 0x96, 0x24, 0x2d, 0xfa, 0xff, 0xfc, 0x61, 0x92, 0xac, 0xac, 0x2d, 0x78, 0x08, 0xcc, 0xf3,
	0x31, 0x61, 0x9e, 0x19, 0x48, 0xac, 0xe1, 0x45, 0xd3, 0x97, 0xca, 0x3f, 0xae, 0x8d, 0x28, 0x3a,
	0x5d, 0x8b, 0xb6, 0xa8, 0x1c, 0xcf, 0x77, 0x46, 0x3b, 0x4d, 0xe2, 0x40, 0xe4, 0x4e, 0x6f, 0x85,
	0x4a, 0xbf, 0x10, 0xe0, 0xf5, 0xcb, 0x03, 0x21, 0x10, 0xb9, 0x0f, 0x59, 0x53, 0x94, 0xa0, 0x6c,
	0xc1, 0x42, 0x4d, 0x2e, 0xe0, 0xa8, 0xd5, 0x7c, 0xeb, 0x64, 0x27, 0xe8, 0xbf, 0x04, 0x65, 0x98,
	0x1d, 0x30, 0xb9, 0x84, 0x45, 0xe5, 0x41, 0x53, 0xda, 0x86, 0xe2, 0xd0, 0xf4, 0x4b, 0x90, 0x2b,
	0x38, 0xe6, 0x5a, 0xbd, 0x4b, 0xd3, 0x95, 0x4e, 0x6a, 0x65, 0x69, 0x14, 0xda, 0xa7, 0x24, 0x49,
	0x01, 0x0f, 0x52, 0xd1, 0x59, 0x82, 0xb3, 0x78, 0x75, 0x92, 0x8f, 0xc6, 0xca, 0x37, 0x52, 0x31,
	0x2f, 0x92, 0x6b, 0x88, 0x06, 0xdd, 0x3b, 0x3a, 0x0f, 0xa6, 0xd3, 0xa9, 0x49, 0xf7, 0x8e, 0x05,
	0x39, 0x7d, 0x83, 0xc8, 0x23, 0x72, 0x06, 0xb3, 0xa1, 0x6c, 0x7b, 0x11, 0x72, 0x20, 0xb6, 0x07,
	0xe4, 0x1e, 0x96, 0x96, 0x1b, 0xb9, 0x73, 0x4f, 0x7d, 0xf5, 0x28, 0x3e, 0x43, 0x98, 0x78, 0x75,
	0x3e, 0xf9, 0xec, 0x79, 0x64, 0x60, 0x13, 0x7b, 0x7a, 0x03, 0xcb, 0xb1, 0xea, 0xb3, 0x97, 0x75,
	0x6d, 0x84, 0xb5, 0xc2, 0x52, 0x94, 0x60, 0x9f, 0xfd, 0x40, 0xa4, 0xb7, 0x80, 0x37, 0x52, 0xfd,
	0xb9, 0x50, 0xf2, 0x13, 0x66, 0xbf, 0xcc, 0x50, 0xaf, 0xff, 0xbf, 0xce, 0xc2, 0x00, 0xd5, 0x3c,
	0x5c, 0xe7, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x88, 0x20, 0x5e, 0x82, 0xc1, 0x01, 0x00, 0x00,
}
