// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/database/types/record/record.proto

package record

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/packtumi9722/huanhuanhuei/src/database/types/reply"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordDatum struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordDatum) Reset()         { *m = RecordDatum{} }
func (m *RecordDatum) String() string { return proto.CompactTextString(m) }
func (*RecordDatum) ProtoMessage()    {}
func (*RecordDatum) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{0}
}

func (m *RecordDatum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordDatum.Unmarshal(m, b)
}
func (m *RecordDatum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordDatum.Marshal(b, m, deterministic)
}
func (m *RecordDatum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordDatum.Merge(m, src)
}
func (m *RecordDatum) XXX_Size() int {
	return xxx_messageInfo_RecordDatum.Size(m)
}
func (m *RecordDatum) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordDatum.DiscardUnknown(m)
}

var xxx_messageInfo_RecordDatum proto.InternalMessageInfo

func (m *RecordDatum) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RecordData struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordData) Reset()         { *m = RecordData{} }
func (m *RecordData) String() string { return proto.CompactTextString(m) }
func (*RecordData) ProtoMessage()    {}
func (*RecordData) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{1}
}

func (m *RecordData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordData.Unmarshal(m, b)
}
func (m *RecordData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordData.Marshal(b, m, deterministic)
}
func (m *RecordData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordData.Merge(m, src)
}
func (m *RecordData) XXX_Size() int {
	return xxx_messageInfo_RecordData.Size(m)
}
func (m *RecordData) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordData.DiscardUnknown(m)
}

var xxx_messageInfo_RecordData proto.InternalMessageInfo

func (m *RecordData) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordID struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordID) Reset()         { *m = RecordID{} }
func (m *RecordID) String() string { return proto.CompactTextString(m) }
func (*RecordID) ProtoMessage()    {}
func (*RecordID) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{2}
}

func (m *RecordID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordID.Unmarshal(m, b)
}
func (m *RecordID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordID.Marshal(b, m, deterministic)
}
func (m *RecordID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordID.Merge(m, src)
}
func (m *RecordID) XXX_Size() int {
	return xxx_messageInfo_RecordID.Size(m)
}
func (m *RecordID) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordID.DiscardUnknown(m)
}

var xxx_messageInfo_RecordID proto.InternalMessageInfo

func (m *RecordID) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

type RecordIDs struct {
	Txhashes             []string `protobuf:"bytes,1,rep,name=txhashes,proto3" json:"txhashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordIDs) Reset()         { *m = RecordIDs{} }
func (m *RecordIDs) String() string { return proto.CompactTextString(m) }
func (*RecordIDs) ProtoMessage()    {}
func (*RecordIDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{3}
}

func (m *RecordIDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordIDs.Unmarshal(m, b)
}
func (m *RecordIDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordIDs.Marshal(b, m, deterministic)
}
func (m *RecordIDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordIDs.Merge(m, src)
}
func (m *RecordIDs) XXX_Size() int {
	return xxx_messageInfo_RecordIDs.Size(m)
}
func (m *RecordIDs) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordIDs.DiscardUnknown(m)
}

var xxx_messageInfo_RecordIDs proto.InternalMessageInfo

func (m *RecordIDs) GetTxhashes() []string {
	if m != nil {
		return m.Txhashes
	}
	return nil
}

type Record struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromToken            *TokenDetail `protobuf:"bytes,2,opt,name=fromToken,proto3" json:"fromToken,omitempty"`
	ToToken              *TokenDetail `protobuf:"bytes,3,opt,name=toToken,proto3" json:"toToken,omitempty"`
	Exrate               float64      `protobuf:"fixed64,4,opt,name=exrate,proto3" json:"exrate,omitempty"`
	StatusCode           int32        `protobuf:"varint,5,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusTime           *StatusTime  `protobuf:"bytes,6,opt,name=statusTime,proto3" json:"statusTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{4}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Record) GetFromToken() *TokenDetail {
	if m != nil {
		return m.FromToken
	}
	return nil
}

func (m *Record) GetToToken() *TokenDetail {
	if m != nil {
		return m.ToToken
	}
	return nil
}

func (m *Record) GetExrate() float64 {
	if m != nil {
		return m.Exrate
	}
	return 0
}

func (m *Record) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Record) GetStatusTime() *StatusTime {
	if m != nil {
		return m.StatusTime
	}
	return nil
}

type TokenDetail struct {
	Txhash               string   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TokenValue           string   `protobuf:"bytes,4,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
	TokenDecimal         int32    `protobuf:"varint,5,opt,name=tokenDecimal,proto3" json:"tokenDecimal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenDetail) Reset()         { *m = TokenDetail{} }
func (m *TokenDetail) String() string { return proto.CompactTextString(m) }
func (*TokenDetail) ProtoMessage()    {}
func (*TokenDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{5}
}

func (m *TokenDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenDetail.Unmarshal(m, b)
}
func (m *TokenDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenDetail.Marshal(b, m, deterministic)
}
func (m *TokenDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDetail.Merge(m, src)
}
func (m *TokenDetail) XXX_Size() int {
	return xxx_messageInfo_TokenDetail.Size(m)
}
func (m *TokenDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDetail proto.InternalMessageInfo

func (m *TokenDetail) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *TokenDetail) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *TokenDetail) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TokenDetail) GetTokenValue() string {
	if m != nil {
		return m.TokenValue
	}
	return ""
}

func (m *TokenDetail) GetTokenDecimal() int32 {
	if m != nil {
		return m.TokenDecimal
	}
	return 0
}

type StatusTime struct {
	PendingTime          int64    `protobuf:"varint,1,opt,name=pendingTime,proto3" json:"pendingTime,omitempty"`
	FinishedTime         int64    `protobuf:"varint,2,opt,name=finishedTime,proto3" json:"finishedTime,omitempty"`
	ConfirmedTime        int64    `protobuf:"varint,3,opt,name=confirmedTime,proto3" json:"confirmedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusTime) Reset()         { *m = StatusTime{} }
func (m *StatusTime) String() string { return proto.CompactTextString(m) }
func (*StatusTime) ProtoMessage()    {}
func (*StatusTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b3903fc871297c, []int{6}
}

func (m *StatusTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusTime.Unmarshal(m, b)
}
func (m *StatusTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusTime.Marshal(b, m, deterministic)
}
func (m *StatusTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusTime.Merge(m, src)
}
func (m *StatusTime) XXX_Size() int {
	return xxx_messageInfo_StatusTime.Size(m)
}
func (m *StatusTime) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusTime.DiscardUnknown(m)
}

var xxx_messageInfo_StatusTime proto.InternalMessageInfo

func (m *StatusTime) GetPendingTime() int64 {
	if m != nil {
		return m.PendingTime
	}
	return 0
}

func (m *StatusTime) GetFinishedTime() int64 {
	if m != nil {
		return m.FinishedTime
	}
	return 0
}

func (m *StatusTime) GetConfirmedTime() int64 {
	if m != nil {
		return m.ConfirmedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*RecordDatum)(nil), "database.types.record.RecordDatum")
	proto.RegisterType((*RecordData)(nil), "database.types.record.RecordData")
	proto.RegisterType((*RecordID)(nil), "database.types.record.RecordID")
	proto.RegisterType((*RecordIDs)(nil), "database.types.record.RecordIDs")
	proto.RegisterType((*Record)(nil), "database.types.record.Record")
	proto.RegisterType((*TokenDetail)(nil), "database.types.record.TokenDetail")
	proto.RegisterType((*StatusTime)(nil), "database.types.record.StatusTime")
}

func init() {
	proto.RegisterFile("src/database/types/record/record.proto", fileDescriptor_37b3903fc871297c)
}

var fileDescriptor_37b3903fc871297c = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x63, 0x87, 0x3a, 0xf1, 0x49, 0x61, 0x71, 0x24, 0x90, 0x65, 0x6e, 0xee, 0xa8, 0x82,
	0xac, 0x1c, 0xa9, 0x08, 0xb1, 0x61, 0xc1, 0xc5, 0x08, 0x75, 0xc9, 0x34, 0xb0, 0x60, 0x37, 0xcd,
	0x4c, 0xc8, 0x88, 0xf8, 0x22, 0xcf, 0x44, 0x4a, 0x5e, 0x80, 0x17, 0xe0, 0x09, 0x78, 0x53, 0xe4,
	0x99, 0x71, 0xe2, 0xa8, 0x4d, 0xd3, 0x8d, 0xad, 0xf3, 0xfb, 0xfb, 0xff, 0x73, 0xce, 0xc8, 0x36,
	0xbc, 0x52, 0xf5, 0x6c, 0xc2, 0x99, 0x66, 0xd7, 0x4c, 0x89, 0x89, 0xde, 0x54, 0x42, 0x4d, 0x6a,
	0x31, 0x2b, 0x6b, 0xee, 0x6e, 0x69, 0x55, 0x97, 0xba, 0xc4, 0xc7, 0x2d, 0x93, 0x1a, 0x26, 0xb5,
	0x0f, 0xe3, 0xf3, 0x5b, 0xed, 0xd5, 0x72, 0x63, 0xaf, 0xd6, 0x4c, 0x32, 0x18, 0x51, 0xc3, 0x67,
	0x4c, 0xaf, 0x72, 0x7c, 0x0b, 0x81, 0xb5, 0x47, 0x5e, 0xe2, 0x8d, 0x47, 0x17, 0xcf, 0xd3, 0x5b,
	0xc3, 0x53, 0xeb, 0xa1, 0x0e, 0x26, 0x5f, 0x00, 0xb6, 0x29, 0x0c, 0xdf, 0xc1, 0xc0, 0xea, 0x2a,
	0xf2, 0x92, 0xfe, 0xf1, 0x94, 0x96, 0x26, 0x04, 0x86, 0x56, 0xba, 0xcc, 0xf0, 0x09, 0x04, 0x7a,
	0xbd, 0x60, 0x6a, 0x61, 0x26, 0x09, 0xa9, 0xab, 0xc8, 0x6b, 0x08, 0x5b, 0x46, 0x61, 0x0c, 0x43,
	0x2b, 0x0b, 0xdb, 0x2a, 0xa4, 0xdb, 0x9a, 0xfc, 0xf5, 0x21, 0xb0, 0x24, 0x3e, 0x02, 0x5f, 0x72,
	0x97, 0xe3, 0x4b, 0x8e, 0x1f, 0x20, 0x9c, 0xd7, 0x65, 0x3e, 0x2d, 0x7f, 0x8b, 0x22, 0xf2, 0xcd,
	0xa2, 0xe4, 0xc0, 0x88, 0x86, 0xc9, 0x84, 0x66, 0x72, 0x49, 0x77, 0x26, 0x7c, 0x0f, 0x03, 0x5d,
	0x5a, 0x7f, 0xff, 0xde, 0xfe, 0xd6, 0xd2, 0xec, 0x26, 0xd6, 0x35, 0xd3, 0x22, 0x7a, 0x90, 0x78,
	0x63, 0x8f, 0xba, 0x0a, 0x5f, 0x00, 0x28, 0xcd, 0xf4, 0x4a, 0x7d, 0x2e, 0xb9, 0x88, 0x4e, 0x12,
	0x6f, 0x7c, 0x42, 0x3b, 0x0a, 0x7e, 0x6c, 0x9f, 0x4f, 0x65, 0x2e, 0xa2, 0xc0, 0x34, 0x3e, 0x3b,
	0xd0, 0xf8, 0x6a, 0x0b, 0xd2, 0x8e, 0x89, 0xfc, 0xf3, 0x60, 0xd4, 0x99, 0xe9, 0xd0, 0x31, 0xe3,
	0x33, 0x08, 0x75, 0x83, 0x4d, 0x37, 0x95, 0x30, 0x47, 0x14, 0xd2, 0x9d, 0x80, 0x11, 0x0c, 0x18,
	0xe7, 0xb5, 0x50, 0xca, 0xac, 0x1f, 0xd2, 0xb6, 0x6c, 0x56, 0x30, 0xd8, 0x0f, 0xb6, 0x5c, 0xd9,
	0xf5, 0x42, 0xda, 0x51, 0x90, 0xc0, 0xa9, 0xb6, 0xed, 0x67, 0x32, 0x67, 0x4b, 0xb7, 0xe4, 0x9e,
	0x46, 0xd6, 0x00, 0xbb, 0xe9, 0x31, 0x81, 0x51, 0x25, 0x0a, 0x2e, 0x8b, 0x5f, 0x66, 0xeb, 0x66,
	0xcc, 0x3e, 0xed, 0x4a, 0x4d, 0xe6, 0x5c, 0x16, 0x52, 0x2d, 0x04, 0x37, 0x88, 0x6f, 0x90, 0x3d,
	0x0d, 0xcf, 0xe1, 0xe1, 0xac, 0x2c, 0xe6, 0xb2, 0xce, 0x1d, 0xd4, 0x37, 0xd0, 0xbe, 0x78, 0xf1,
	0xc7, 0x87, 0x61, 0xe6, 0x8e, 0x13, 0x29, 0x84, 0x5f, 0x85, 0x76, 0xaf, 0xd0, 0xcb, 0x3b, 0x5f,
	0xe1, 0xcb, 0x2c, 0x26, 0x77, 0x02, 0xe6, 0xeb, 0x22, 0x3d, 0xbc, 0x02, 0xd8, 0x66, 0x2a, 0x4c,
	0x8e, 0x84, 0xaa, 0xf8, 0xec, 0x58, 0x2a, 0x23, 0x3d, 0xfc, 0x06, 0xa7, 0xdf, 0x2b, 0xce, 0xb4,
	0x70, 0xb3, 0xde, 0x63, 0x94, 0xf8, 0xe9, 0x4d, 0xa6, 0xf9, 0x29, 0xd0, 0xe6, 0x4a, 0x7a, 0x9f,
	0x86, 0x3f, 0xdd, 0xa7, 0x7d, 0x1d, 0x98, 0xff, 0xc4, 0x9b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0x81, 0xac, 0xc0, 0x8e, 0x04, 0x00, 0x00,
}
